---
version: "2.1"
services:

  nginx:
    container_name: nginx
    hostname: nginx
    build: ${PWD}/nginx
    networks:
      - stack
    ports:
      - 80:8080
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped
    depends_on:
      shiny:
        condition: service_started

  shiny:
    container_name: shiny
    hostname: shiny
    build: ${PWD}/shiny-server
    networks:
      - stack
    volumes:
      - ./shiny-server/shiny/:/srv/shiny-server/:ro
      - ./logs/shiny/:/var/log/shiny-server/
    restart: unless-stopped

networks:
  stack:
